version: '3.8' # Specifies the Docker Compose file format version

services:
  # Qdrant Vector Database Service
  qdrant:
    image: qdrant/qdrant:latest
    container_name: grok_stem_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - grok_stem_network
    restart: unless-stopped

  # Backend Service (FastAPI)
  backend:
    container_name: grok_stem_backend
    build:
      context: ./backend         # build from your backend folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend   # <-- mount into /app/backend, not /app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app          # <-- so 'import backend' finds /app/backend
    networks:
      - grok_stem_network
    depends_on:
      qdrant:
        condition: service_started
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Service (React/Vite)
  frontend:
    container_name: grok_stem_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - grok_stem_network
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_WEBSOCKET_URL=ws://localhost:8000/ws

volumes:
  qdrant_storage:

networks:
  grok_stem_network:
    driver: bridge
